trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git diff
  displayName: "Synchroniser GitHub avec Azure DevOps"