trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
    echo "branch"
    git branch
    echo "fetch origin"
    git fetch origin
  displayName: "Synchroniser GitHub main avec Azure DevOps main"
