trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git remote add azure "https://dev.azure.com/tlonchampt/_git/armand"
    git pull origin main
    git push azure main:master --force
  displayName: "Synchroniser GitHub main avec Azure DevOps master"
