trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
    cd
    git log
    git branch
    echo "pull"
    git pull origin main
  displayName: "Synchroniser GitHub main avec Azure DevOps main"
