trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
    git branch
  displayName: "Synchroniser GitHub main avec Azure DevOps main"
