trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:

- script: |
    git branch
    git remote add azure https://tlonchampt2@dev.azure.com/tlonchampt2/armand/_git/armand
    git push azure HEAD
    git remote remove azure || exit 0
  displayName: "Synchroniser GitHub main avec Azure DevOps main"
