trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
    git remote remove azure || exit 0
    git remote add azure "https://dev.azure.com/tlonchampt/armand/_git/armand"
    git pull origin main
    git push azure main --force
  displayName: "Synchroniser GitHub main avec Azure DevOps main"
