trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
    git remote add azure https://tlonchampt2@dev.azure.com/tlonchampt2/armand/_git/armand
    git push azure main --force
  displayName: "Synchroniser GitHub main avec Azure DevOps main"

