trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git branch
  displayName: "Supprimer toutes les branches du dépôt Azure DevOps"
